"""
    uCentral gateway API

    A process to manage configuration for devices.  # noqa: E501

    The version of the OpenAPI document: 0.0.8
    Contact: ucentralsupport@arilia.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.generic_good_answer import GenericGoodAnswer


class TestGenericGoodAnswer(unittest.TestCase):
    """GenericGoodAnswer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGenericGoodAnswer(self):
        """Test GenericGoodAnswer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GenericGoodAnswer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
