"""
    uCentral gateway API

    A process to manage configuration for devices.  # noqa: E501

    The version of the OpenAPI document: 0.0.8
    Contact: ucentralsupport@arilia.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.device_type import DeviceType
globals()['DeviceType'] = DeviceType
from openapi_client.model.device_with_status import DeviceWithStatus


class TestDeviceWithStatus(unittest.TestCase):
    """DeviceWithStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeviceWithStatus(self):
        """Test DeviceWithStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DeviceWithStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
