"""
    uCentral gateway API

    A process to manage configuration for devices.  # noqa: E501

    The version of the OpenAPI document: 0.0.8
    Contact: ucentralsupport@arilia.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.device_with_status import DeviceWithStatus
globals()['DeviceWithStatus'] = DeviceWithStatus
from openapi_client.model.device_list_with_status import DeviceListWithStatus


class TestDeviceListWithStatus(unittest.TestCase):
    """DeviceListWithStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeviceListWithStatus(self):
        """Test DeviceListWithStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DeviceListWithStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
