"""
    uCentral gateway API

    A process to manage configuration for devices.  # noqa: E501

    The version of the OpenAPI document: 0.0.8
    Contact: ucentralsupport@arilia.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.configurations_api import ConfigurationsApi  # noqa: E501


class TestConfigurationsApi(unittest.TestCase):
    """ConfigurationsApi unit test stubs"""

    def setUp(self):
        self.api = ConfigurationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_default_configuration(self):
        """Test case for create_default_configuration

        Create a default configuration  # noqa: E501
        """
        pass

    def test_delete_default_configuration(self):
        """Test case for delete_default_configuration

        Delete a default default configuration  # noqa: E501
        """
        pass

    def test_get_default_configuration(self):
        """Test case for get_default_configuration

        Retrieve a default configuration  # noqa: E501
        """
        pass

    def test_get_default_configurations(self):
        """Test case for get_default_configurations

        Retrieve the lists of all default configurations  # noqa: E501
        """
        pass

    def test_update_default_configuration(self):
        """Test case for update_default_configuration

        Update a default configuration  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
