"""
    uCentral gateway API

    A process to manage configuration for devices.  # noqa: E501

    The version of the OpenAPI document: 0.0.8
    Contact: ucentralsupport@arilia.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.devices_api import DevicesApi  # noqa: E501


class TestDevicesApi(unittest.TestCase):
    """DevicesApi unit test stubs"""

    def setUp(self):
        self.api = DevicesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_new_device(self):
        """Test case for create_new_device

        Creating a new device  # noqa: E501
        """
        pass

    def test_delete_device(self):
        """Test case for delete_device

        Deleting a single device  # noqa: E501
        """
        pass

    def test_get_device_information(self):
        """Test case for get_device_information

        Retrieve information for a single device  # noqa: E501
        """
        pass

    def test_get_device_list(self):
        """Test case for get_device_list

        Returns a list of devices.  # noqa: E501
        """
        pass

    def test_update_new_device(self):
        """Test case for update_new_device

        Updating a new device  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
