"""
    uCentral gateway API

    A process to manage configuration for devices.  # noqa: E501

    The version of the OpenAPI document: 0.0.8
    Contact: ucentralsupport@arilia.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.tag_value_pair import TagValuePair


class TestTagValuePair(unittest.TestCase):
    """TagValuePair unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTagValuePair(self):
        """Test TagValuePair"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TagValuePair()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
