"""
    uCentral gateway API

    A process to manage configuration for devices.  # noqa: E501

    The version of the OpenAPI document: 0.0.8
    Contact: ucentralsupport@arilia.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.files_api import FilesApi  # noqa: E501


class TestFilesApi(unittest.TestCase):
    """FilesApi unit test stubs"""

    def setUp(self):
        self.api = FilesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_upload_fidelete(self):
        """Test case for delete_upload_fidelete

        Delete a file from the upload directory  # noqa: E501
        """
        pass

    def test_get_upload_file(self):
        """Test case for get_upload_file

        Get a file from the upload directory  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
