"""
    uCentral gateway API

    A process to manage configuration for devices.  # noqa: E501

    The version of the OpenAPI document: 0.0.8
    Contact: ucentralsupport@arilia.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.statistics_details import StatisticsDetails
globals()['StatisticsDetails'] = StatisticsDetails
from openapi_client.model.statistics_records import StatisticsRecords


class TestStatisticsRecords(unittest.TestCase):
    """StatisticsRecords unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStatisticsRecords(self):
        """Test StatisticsRecords"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StatisticsRecords()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
