"""
    uCentral gateway API

    A process to manage configuration for devices.  # noqa: E501

    The version of the OpenAPI document: 0.0.8
    Contact: ucentralsupport@arilia.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.system_commands_api import SystemCommandsApi  # noqa: E501


class TestSystemCommandsApi(unittest.TestCase):
    """SystemCommandsApi unit test stubs"""

    def setUp(self):
        self.api = SystemCommandsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_system_command(self):
        """Test case for system_command

        Perform some systeme wide commands  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
