"""
    uCentral gateway API

    A process to manage configuration for devices.  # noqa: E501

    The version of the OpenAPI document: 0.0.8
    Contact: ucentralsupport@arilia.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.tag_value_pair import TagValuePair
globals()['TagValuePair'] = TagValuePair
from openapi_client.model.tag_value_pair_list import TagValuePairList


class TestTagValuePairList(unittest.TestCase):
    """TagValuePairList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTagValuePairList(self):
        """Test TagValuePairList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TagValuePairList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
