"""
    uCentral gateway API

    A process to manage configuration for devices.  # noqa: E501

    The version of the OpenAPI document: 0.0.8
    Contact: ucentralsupport@arilia.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.ouis_api import OUIsApi  # noqa: E501


class TestOUIsApi(unittest.TestCase):
    """OUIsApi unit test stubs"""

    def setUp(self):
        self.api = OUIsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_ouis(self):
        """Test case for get_ouis

        Get a list of OUIs  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
