"""
    uCentral gateway API

    A process to manage configuration for devices.  # noqa: E501

    The version of the OpenAPI document: 0.0.8
    Contact: ucentralsupport@arilia.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.any_payload import AnyPayload


class TestAnyPayload(unittest.TestCase):
    """AnyPayload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnyPayload(self):
        """Test AnyPayload"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AnyPayload()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
