"""
    uCentral gateway API

    A process to manage configuration for devices.  # noqa: E501

    The version of the OpenAPI document: 0.0.8
    Contact: ucentralsupport@arilia.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.name_value_pair import NameValuePair
globals()['NameValuePair'] = NameValuePair
from openapi_client.model.interface_statistics import InterfaceStatistics


class TestInterfaceStatistics(unittest.TestCase):
    """InterfaceStatistics unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInterfaceStatistics(self):
        """Test InterfaceStatistics"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InterfaceStatistics()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
