"""
    uCentral gateway API

    A process to manage configuration for devices.  # noqa: E501

    The version of the OpenAPI document: 0.0.8
    Contact: ucentralsupport@arilia.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.statistics_details import StatisticsDetails


class TestStatisticsDetails(unittest.TestCase):
    """StatisticsDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStatisticsDetails(self):
        """Test StatisticsDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StatisticsDetails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
