"""
    uCentral gateway API

    A process to manage configuration for devices.  # noqa: E501

    The version of the OpenAPI document: 0.0.8
    Contact: ucentralsupport@arilia.com
    Generated by: https://openapi-generator.tech
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "openapi-client"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = [
  "urllib3 >= 1.25.3",
  "python-dateutil",
]

setup(
    name=NAME,
    version=VERSION,
    description="uCentral gateway API",
    author="Arilia Support",
    author_email="ucentralsupport@arilia.com",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "uCentral gateway API"],
    python_requires=">=3.6",
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    license="BSD3",
    long_description="""\
    A process to manage configuration for devices.  # noqa: E501
    """
)
